config/routes.rb
App::Application.routes.draw do
  resources :infos

   root :to => 'infos#index'

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :age, :company, :name


def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  
  else
    scoped
  end
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
     helper_method :sort_column, :sort_direction
  # GET /infos.json

  def sort_column
    Info.column_names.include?(params[:sort]) ? params[:sort] : "name"
    
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  def index

    @infos = Info.all
    @infos = Info.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
   def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:age, :company, :name )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	

def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end


end

app/helpers/infos_helper.rb
module InfosHelper
	
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/_infos.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @infos %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>
<br>
<br>


<%= form_tag infos_path, :method => 'get', :id => "infos_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="infos"><%= render 'infos' %></div>
<% end %>

<br><br>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.name %></td>
    <td><%= info.age %></td>
    <td><%= info.company %></td>
    <td><%= link_to 'Show', info %></td>
    <td><%= link_to 'Edit', edit_info_path(info) %></td>
    <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @info.name %>
</p>

<p>
  <b>Age:</b>
  <%= @info.age %>
</p>

<p>
  <b>Company:</b>
  <%= @info.company %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>